---
image: "registry.gitlab.com/eyeo/docker/v8-project_gitlab-runner:202004.1"

stages:
  - lint_commit
  - build

lint_commit:
  stage: lint_commit
  before_script:
    - sudo apt-get update
    - sudo apt-get install -yyq python3.6
  script: python3.6 .gitlab-ci/check-first-parent.py
  except:
    - master

.job_template: &common_build_v8_lib
  stage: build
  before_script:
    - sudo dpkg --add-architecture i386
    - sudo apt-get update
    - sudo apt-get install -yyq python python3.6 python3-requests build-essential libgtk2.0-dev libc6:i386 xz-utils
  artifacts:
    paths:
      - build/v8-bd6a44fb-includes.tar.xz
      - build/v8-bd6a44fb-arm-android.tar.xz
      - build/v8-bd6a44fb-arm64-android.tar.xz
      - build/v8-bd6a44fb-ia32-android.tar.xz
      - build/v8-bd6a44fb-x64-android.tar.xz

build:
  <<: *common_build_v8_lib
  script:
    - make all
  except:
    - schedules

update:
  <<: *common_build_v8_lib
  script:
    - make update
  only:
    - master
    - schedules
