---
.common:
  tags:
    - &BUILD_IMAGE "registry.gitlab.com/eyeo/docker/v8-project_gitlab-runner:202011.1"

stages:
  - lint_commit
  - needs_update
  - build
  - publish

lint_commit:
  stage: lint_commit
  image:
    *BUILD_IMAGE
  script: python3.6 .gitlab-ci/check-first-parent.py
  except:
    - master

needs_update:
  stage: needs_update
  image:
    *BUILD_IMAGE
  script:
    - make check_up_to_date ||
      echo BASE_NAME=$(make get_base_name) > base_name.env
  artifacts:
    reports:
      dotenv: base_name.env
  only:
    - master
    - schedules

build:
  stage: build
  image:
    *BUILD_IMAGE
  dependencies:
    - needs_update
  script:
    - |
      set -x
      if [ -z "$BASE_NAME" ]; then
        echo "New base revision not found, nothing to do"
        exit 0
      fi
      make all
  artifacts:
    paths:
      - build/*.tar.xz
      - build/info

publish:
  stage: publish
  dependencies:
    - needs_update
    - build
  variables:
    DESTDIR: /var/www/v8.eyeofiles.com/$BASE_NAME
  script:
    - |
      set -x
      if [ -z "$BASE_NAME" ]; then
        echo "New base revision not found, nothing to do"
        exit 0
      fi
      mkdir -p $DESTDIR/
      cp -av $CI_PROJECT_DIR/build/* $DESTDIR/
  tags:
    - eyeofiles-1
  only:
    - master
